Genetec/DAP

- EventMonitoringSample/Certificates/EventMonitoringSample.exe.cert
- EventMonitoringSample/EventMonitoringSample.csproj
- EventMonitoringSample/Program.cs
- Genetec.Dap.CodeSamples.sln
> EventMonitoring sample

- CredentialBuilderSample/App.config
- CredentialBuilderSample/Certificates/CredentialBuilderSample.exe.cert
- CredentialBuilderSample/CredentialBuilderSample.csproj
- CredentialBuilderSample/Program.cs
- CredentialBuilderSample/Properties/AssemblyInfo.cs
- Genetec.Dap.CodeSamples.sln
> CredentialBuilder sample

- Genetec.Dap.CodeSamples.sln
New feature addition.
Adds two new projects, "DisplayInTileSample" and "CustomEntitySample", to the "Genetec.Dap.CodeSamples.sln" solution.
> Add missing projects to solution

- BackgroundProcessSample/BackgroundProcessPage.cs
- BackgroundProcessSample/BackgroundProcessPageDescriptor.cs
- BackgroundProcessSample/BackgroundProcessPageView.xaml
- BackgroundProcessSample/BackgroundProcessPageView.xaml.cs
- BackgroundProcessSample/BackgroundProcessPageViewModel.cs
- BackgroundProcessSample/SampleModule.cs
Update UI, simplify code, and refresh license
> BackgroundProcess sample

- DisplayInTileSample/Program.cs
This pull request introduces a significant refactors display logic, and enhances asynchronous operations and monitor handling for improved functionality and code cleanliness.
> DisplayInTile sample

- CustomEventSample/Program.cs
Code refactoring and enhancements, error handling improvements, and a license update.
- Added copyright and Apache License, Version 2.0 information at the beginning of the namespace declaration.
- Implemented asynchronous login and custom event handling methods with comprehensive error handling.
- Refactored code to improve readability and maintainability, including the introduction of variables for `customEventId` and `cameraGuid`.
- Removed redundant code and improved user feedback mechanisms.
- Enhanced custom event functionality with new methods for event creation, retrieval, and raising.
> CustomEvent sample

- CustomFieldSample/Program.cs
- Updated copyright notice to 2024 and switched to Apache License 2.0.
- Introduced new constants `customFieldName` and `customFieldNameValue` for handling a custom "Employee ID" field.
- Implemented methods for custom field management, including listing, detailing, creating/updating, and integrating custom fields with cardholder entities.
- Refined logic for custom field and cardholder creation, including better console feedback on operations.
- Improved the query and print logic for cardholder information based on custom field values, offering clearer console output.
> CustomField sample

- EntityCacheSample/EntityCacheSample.csproj
- EntityCacheSample/Program.cs
- Updated the licensing to Apache License, Version 2.0, reflecting more flexible usage terms.
- Introduced `consoleLock` for synchronized console output across different threads.
- Refactored event handling with named methods (`OnEntitiesAdded`, `OnEntitiesInvalidated`, `OnEntitiesRemoved`) for better code organization.
- Enhanced the `PrintEntityCache` and `LoadEntities` methods for improved operational feedback and monitoring.
> EntityCache sample

- PeopleCountingSample/PeopleCountingSample.csproj
- PeopleCountingSample/Program.cs
Code cleanup and license update, and functionality improvements.
> PeopleCounting sample

- CustomEntitySample/CustomEntitySample.csproj
- CustomEntitySample/Program.cs
- Updated copyright notice and switched to Apache License 2.0.
- Introduced a constant for `customEntityId` for better maintainability.
- Implemented new methods for managing custom entities, including creation, update, display, and querying functionalities.
- Improved error handling for logon failures with explicit user feedback.
- Refined custom entity type creation logic to prevent duplicate entries and enhanced descriptor properties for better categorization.
- Developed asynchronous methods for creating and querying custom entities, ensuring atomic operations and detailed output.
- Cleaned up the codebase by removing redundant code and improving readability and organization.
> CustomEntity sample

- BadgePrinterSample/BadgePrinterSample.csproj
- BadgePrinterSample/Certificates/Genetec.Dap.CodeSamples.SampleBadgePrinter.cert
- BadgePrinterSample/Properties/AssemblyInfo.cs
- BadgePrinterSample/SampleBadgePrinter.cs
- BadgePrinterSample/SampleModule.cs
- Genetec.Dap.CodeSamples.sln
- Added `BadgePrinterSample` project to Solution.
- Implemented `SampleBadgePrinter` class inheriting from `BadgePrinter` with custom print job logic.
- Implemented `SampleModule` class for module initialization and registration.
- Added certificate file `Genetec.Dap.CodeSamples.SampleBadgePrinter.cert` for SDK authentication.
> Add BadgePrinterSample project

- PtzCoordinatesManagerSample/Program.cs
- PtzCoordinatesManagerSample/PtzCoordinatesManagerSample.csproj
- Updated license to Apache 2.0 and copyright year to 2024.
- Introduced comprehensive PTZ camera control workflow.
- Improved error handling and added logging for PTZ operations.
- Updated C# language version to 9 in PtzCoordinatesManagerSample.csproj.
- Conducted general code cleanup for better organization and maintainability.
> PtzCoordinatesManager sample

- CameraSample/CameraSample.csproj
Added a reference to `WindowsBase` in `CameraSample.csproj` to support WPF and Windows-based functionality.
> Camera sample

- AuditTrailsSample/App.config
- AuditTrailsSample/AuditTrailsSample.csproj
- AuditTrailsSample/Certificates/AuditTrailsSample.exe.cert
- AuditTrailsSample/Program.cs
- Genetec.Dap.CodeSamples.sln
Implemented `Program.cs` for audit trail retrieval and display, including an `AuditTrail` record type.
> Add AuditTrailsSample project

- ActivityTrailsSample/ActivityTrailsSample.csproj
- ActivityTrailsSample/App.config
- ActivityTrailsSample/Certificates/ActivityTrailsSample.exe.cert
- ActivityTrailsSample/Program.cs
- Genetec.Dap.CodeSamples.sln
This commit introduces the ActivityTrailsSample project to the Genetec.Dap.CodeSamples solution.
The main Program.cs demonstrates SDK usage for querying activity trails.
> Add ActivityTrailsSample project

- Samples/Platform SDK/LoginManagerSample/Program.cs
Moved namespace and using directives to the top of the file. Removed static constructor and made Main method async. Added comments for Security Center server connection parameters. Ensured proper disposal of Engine instance with using statement. Added detailed logging event handlers for logon status changes. Introduced CancellationTokenSource for login process cancellation. Handled user cancellation requests with Console.CancelKeyPress. Updated LogOnAsync to include cancellation token.
Improved failed login log message with failure code and error. Changed Console.ReadKey to prevent key press display.
> LoginManager sample

- Samples/Platform SDK/CameraConfigurationSample/Program.cs
- Added copyright and license information at the top of `Program.cs`.
- Refactored main logic into an asynchronous method `RunSample`.
- Updated main program flow to call `RunSample`.
- Moved exit prompt statements to the main program flow.
- Refactored and moved `LoadCameras`, `GetCameraConfigurations`, and `DisplayToConsole` methods inside `RunSample`.
- Removed redundant `else` block and old exit prompt statements.
- Updated `CreateFromDataRow` to be inline within `GetCameraConfigurations`.
- Cleaned up unnecessary comments and redundant code blocks.
> CameraConfiguration sample

- Samples/Platform SDK/CredentialBuilderSample/Program.cs
* Significantly refactored the code for better organization.
* Removed redundant using directives to streamline imports.
* Introduced a new `RunSample` method to encapsulate main logic.
* Replaced the `Main` method with an asynchronous approach for improved async handling.
* Added various credential formats for building and displaying credentials.
* Enhanced credential display logic to provide detailed information about each credential type, including unique identifiers and specific properties.
> refactor: ✨ Improve structure and functionality

- Samples/Plugin SDK/CustomActionSample/Client/SampleCustomActionView.xaml.cs
- Samples/Plugin SDK/CustomActionSample/Server/SamplePlugin.cs
Enhance the SamplePlugin functionality by initializing the AssemblyResolver and handling action events.
* SamplePlugin.cs: Added a static constructor to initialize the AssemblyResolver and modified OnPluginLoaded to handle Engine.ActionReceived events.
> CustomAction sample

- Samples/Genetec.Dap.CodeSamples.sln
- Samples/Platform SDK/AccessRuleSample/AccessRuleSample.csproj
- Samples/Platform SDK/AccessRuleSample/App.config
- Samples/Platform SDK/AccessRuleSample/Certificates/AccessRuleSample.exe.cert
- Samples/Platform SDK/AccessRuleSample/Program.cs
Add AccessRuleSample project to the solution
Introduce a new sample project to demonstrate access rule configuration using the SDK.
* Added "AccessRuleSample" project to `Genetec.Dap.CodeSamples.sln` with Debug and Release configurations.
* Created `AccessRuleSample.csproj` defining target framework, output type, and library references.
* Added `App.config` to specify the supported runtime for the application.
* Implemented `Program.cs` to initialize the SDK, connect to a server, and configure access rules.
* Included `AccessRuleSample.exe.cert` with client certificate information for the application.
> AccessRule Sample

- Samples/Platform SDK/CardholderSample/CardholderSample.cs
Enhance cardholder management with credential handling
Improve the functionality and user experience of cardholder management by
adding credential handling and refining existing methods.
* Updated `CardholderSample.cs` to introduce credential handling for
cardholders, including the new method `CreateCardholdersWithCredentials`.
* Removed the old `CreateCardholders` method and integrated its logic into
the new method for better efficiency.
* Enhanced `DisplayCardholderInfo` to show additional details about
cardholder status and credentials.
* Added `FindCredential` method to retrieve credentials based on their
format, preventing duplicate credential creation.
> Enhance cardholder management with credential handling

- Samples/Platform SDK/EntityCacheSample/EntityCacheSample.cs
Eliminate unnecessary logging before user logon to streamline output.
* EntityCacheSample.cs: Removed logging of the entity cache before user logon.
> Remove pre-logon entity cache logging

- Samples/Genetec.Dap.CodeSamples.sln
- Samples/Platform SDK/HardwareInventoryQuerySample/App.config
- Samples/Platform SDK/HardwareInventoryQuerySample/Certificates/HardwareInventoryQuerySample.exe.cert
- Samples/Platform SDK/HardwareInventoryQuerySample/HardwareInventoryInfo.cs
- Samples/Platform SDK/HardwareInventoryQuerySample/HardwareInventoryQuerySample.cs
- Samples/Platform SDK/HardwareInventoryQuerySample/HardwareInventoryQuerySample.csproj
- Samples/Platform SDK/HardwareInventoryQuerySample/Program.cs
This commit introduces a new project for querying hardware inventory, along with necessary configurations and implementations.
To provide a sample application that demonstrates how to retrieve and display hardware inventory information using the Genetec SDK.
* Added a new project called "HardwareInventoryQuerySample" to the solution.
* Updated the solution configuration to include build settings for the new project.
* Introduced a new `HardwareInventoryInfo` record for encapsulating hardware details.
* Implemented the `HardwareInventoryQuerySample` class for retrieving hardware info.
* Added XML configuration for the application, specifying the supported runtime.
* Included a client certificate configuration for the hardware inventory sample.
* Updated the project file for …
> Add HardwareInventoryQuerySample project to solution
